deployments:
  CRM:
    filename:
      ./Dockerfile
    vm_size:
      2GB
  aCRM:
    filename:
      ./Dockerfile
    vm_size:
      2GB
  sCRM:
    filename:
      ./Dockerfile
    vm_size:
      2GB
  dCRM:
    filename:
      ./Dockerfile
    vm_size:
      2GB
  fCRM:
    filename:
      ./Dockerfile
    vm_size:
      2GB
  gCRM:
    filename:
      ./Dockerfile
    vm_size:
      2GB
  hCRM:
    filename:
      ./Dockerfile
    vm_size:
      2GB
  jCRM:
    filename:
      ./Dockerfile
    vm_size:
      2GB
  kCRM:
    filename:
      ./Dockerfile
      
    vm_size:
      2GB
  lCRM:
    filename:
      ./Dockerfile
    vm_size:
      2GB
  zCRM:
    filename:
      ./Dockerfile
    vm_size:
      2GB
  xCRM:
    filename:
      ./Dockerfile
    vm_size:
      2GB
  cCRM:
    filename:
      ./Dockerfile
    vm_size:
      2GB
  vCRM:
    filename:
      ./Dockerfile
    vm_size:
      2GB
  bCRM:
    filename:
      ./Dockerfile
    vm_size:
      2GB
  nCRM:
    filename:
      ./Dockerfile
    vm_size:
      2GB
  mCRM:
    filename:
      ./Dockerfile
    vm_size:
      2GB
  qCRM:
    filename:
      ./Dockerfile
    vm_size:
      2GB
  wCRM:
    filename:
      ./Dockerfile
    vm_size:
      2GB
  eCRM:
    filename:
      ./Dockerfile
    vm_size:
      2GB
  rCRM:
    filename:
      ./Dockerfile
    vm_size:
      2GB
  tCRM:
    filename:
      ./Dockerfile
    vm_size:
      2GB
  yCRM:
    filename:
      ./Dockerfile
    vm_size:
      2GB
  uCRM:
    filename:
      ./Dockerfile
    vm_size:
      2GB
  iCRM:
    filename:
      ./Dockerfile
    vm_size:
      2GB
  oCRM:
    filename:
      ./Dockerfile
    vm_size:
      2GB
  pCRM:
    filename:
      ./Dockerfile
    vm_size:
      2GB
  
